// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1lnZeCrkg1PcIbo6LRgnNQFxunyvT4Q4',
    appId: '1:906024454768:web:5db93c0a400fa1b0df82b5',
    messagingSenderId: '906024454768',
    projectId: 'my-commerce-new',
    authDomain: 'my-commerce-new.firebaseapp.com',
    storageBucket: 'my-commerce-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8lHBPmqq_-IMe9hqkU_hNcJ6N7lGnRU',
    appId: '1:906024454768:android:c7118a1549a02b7fdf82b5',
    messagingSenderId: '906024454768',
    projectId: 'my-commerce-new',
    storageBucket: 'my-commerce-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5PU09A-7_7wa_JL0-ZowiJKzcX-u7e0',
    appId: '1:906024454768:ios:6465a6ed88ac393edf82b5',
    messagingSenderId: '906024454768',
    projectId: 'my-commerce-new',
    storageBucket: 'my-commerce-new.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5PU09A-7_7wa_JL0-ZowiJKzcX-u7e0',
    appId: '1:906024454768:ios:cf8811cf8b0cfcb9df82b5',
    messagingSenderId: '906024454768',
    projectId: 'my-commerce-new',
    storageBucket: 'my-commerce-new.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
